# Generated by Django 4.1.4 on 2022-12-27 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profession',
            options={'verbose_name': 'Profession', 'verbose_name_plural': 'about'},
        ),
        migrations.AddField(
            model_name='profession',
            name='company',
            field=models.TextField(default='SOME STRING', verbose_name='Компания'),
        ),
        migrations.AddField(
            model_name='profession',
            name='habilitis',
            field=models.TextField(default='SOME STRING', verbose_name='Навыки'),
        ),
        migrations.AlterField(
            model_name='profession',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='profession',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Title'),
        ),
    ]
