# Generated by Django 4.1.4 on 2022-12-27 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_alter_profession_options_profession_company_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profession',
            options={'verbose_name': 'Profession', 'verbose_name_plural': 'Table Profesion'},
        ),
        migrations.AddField(
            model_name='profession',
            name='date_vacancy',
            field=models.TextField(default='Дату публикации вакансии.', max_length=20, verbose_name='Дату публикации вакансии.'),
        ),
        migrations.AddField(
            model_name='profession',
            name='region',
            field=models.TextField(default='Название региона', verbose_name='Название региона'),
        ),
        migrations.AddField(
            model_name='profession',
            name='salary',
            field=models.TextField(default='Some string', verbose_name='Оклад'),
        ),
    ]
